# CI build file
language: python
python:
  - "3.4"
  - "2.7"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test --cov=netconnect
after_success:
    - coveralls